# Use postgres/example user/password credentials
version: '3.9'

services:
  vs:
    image: pgvector/pgvector:0.7.4-pg15
    restart: unless-stopped
    ports:
      - "${LOCAL_DB_PORT}:${SERVICE_DB_PORT}"
    # set shared memory limit when using docker-compose
    shm_size: 128mb
 
    volumes:
      - "/srv/vagent:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_DB: "${SERVICE_DB}"
      POSTGRES_USER: "${SERVICE_DB_USER}"
      POSTGRES_PASSWORD: "${SERVICE_DB_PASSWORD}"